### ISSUE TITLE
Please avoid dashes in release numbers

### ISSUE THREAD

**Issue by bdrung** [01org/opa-psm2#22] opened 2017-12-21 10:10 UTC
Debian/Ubuntu uses dashes to separate upstream release numbers from package revisions. Please avoid dashes in release numbers and use just dots.

Can you please clarify the versioning? Looking at the releases, the latest one is labeled with
* IFS_RELEASE_10_6_0_0_134 (which looks like 10.6.0.0.134)
* This code surface corresponds to libpsm2 10.3.8

Looking at the tags, there are PSM2_10.3-8, PSM2_10.3-10, PSM2_10.3-17, PSM2_10.3-37.

**Comment by aravindksg** [comment] 2017-12-21 22:07
The IFS tags represents the commit which are also available through IFS packages (obtained from [Intel OPA site](https://downloadcenter.intel.com/product/92003)). These are more "stable" in that they are exposed to more validation cycles. The "PSM2_*" tagged commits also have testing cycles before being pushed to GitHub, but are not yet released in a known IFS version.

**Comment by rwmcguir** [comment] 2018-05-03 18:33
The actual package version does follow this standard, i.e. all dots. libpsm2-10.3.8.rpm

If you download from github and build a custom version, the Makefile appends the version with an underscore, i.e. libpsm2-10.3.8_0.rpm to indicate you now are potentially different from the upstream. If you make commits into your local repo, it will increment the _0 to _1 etc... showing the number of patches since the base version you downloaded. This makes it easy to track versions between downstream debug, etc...  But still no dashes.  This shows up in the RPM Version field as such
Version: 10.2.8_0
Easy to tell how far diverged from the upstream you are.

Lastly, if you then package that and create and RPM, while not inside a git repo, the package will be tagged with a -1 on the end indicating it was built outside git and thus we can't really find the patch level (i.e.. This is not a version field, but and indication of non-git packaging.  A bit inventive, but still fits the paradigm of packaging deviation and not versions. The version field is still very much intact as intended.
Example:
[root@localhost x86_64]# rpm -qip ./libpsm2-10.2.8_0-1.x86_64.rpm
Name        : libpsm2
Version     : 10.2.8_0

All this to say that the tag here is just abstract and informative. Yes we should change the tag to be more conventional. That is easily doable.

If the other versioning systems are actually causing issues let us know.

**Comment by bdrung** [comment] 2018-05-04 11:04
The underscore is not allowed in Debian in the version (it is used to separate the name and version). You could use the plus sign instead. Other projects use +git if you build from git instead of a release tarball.

**Comment by aravindksg** [comment] 2018-09-27 21:20
The PSM2 version numbers have been fixed to not include dashes in the release numbers. Closing.

**Closed as completed by aravindksg** 2018-09-27 21:20 UTC
